### ISSUE TITLE
Torque slew rate is slow

### ISSUE THREAD

**Issue by collin80** [collin80/GEVCU#69]
This issue could be either in the GEVCU code or in the DMOC or both. When you step on the throttle it doesn't quite respond with the proper haste. There is a lot of throttle smoothing going on on the GEVCU side so that might be the cause or the DMOC might be limiting torque slew rate. This should be investigated and solved one way or the other.

**Comment by neuweiler** [comment]
unless you've integrated my code which artificially adds "slew" to the throttle, the response of the throttle class itself is immediate. It might be that analog inputs add some slew. With a CAN bus throttle and Brusa motor controller, the repsonse is immediate. (that's why I added a slew rate in the ArduinoDue branch)

**Comment by collin80** [comment]
Yes, subsequent to creating this issue we then got the UQM inverter working. It works perfectly fine. It appears that the issue was solely with the DMOC inverter. It apparently has a torque slew rate setting that needs to be changed. This isn't a GEVCU issue. Closing.

**Comment by Isaac96** [comment]
Any recollection on what torque slew rate setting you adjusted in the DMOC? Also, it seems like there's a hard limit on the amps we can draw, or perhaps that's a function of other settings? (Trying to decide if we should replace the controller board on the DMOC with Johannes Huebner's open inverter, but first want to max out the DMOC 645.) Thanks!

**Comment by collin80** [comment]
I don't remember. It has been years since I actually used a DMOC in a car. I have a DMOC "on the bench" if by that I mean "it's kind of hooked up in a heap under a shelf." I will try to connect to that DMOC this week and see if I can find the setting.

**Comment by Isaac96** [comment]
Thanks Collin. My son (and this is his gihub account I'm writing to you on) has gone through all of your GEVCU code while building our car, and has used your CAN library on several arduinos to control various things like a Leaf BMS and Volt DC-DC. Thanks for the great code!

**Comment by Isaac96** [comment]
Collin I wonder if you could send us your par file?
